const SOLID_MATERIAL_REFS = new Set([
  "wood-oak",
  "wood-walnut",
  "laminate-white",
  "laminate-black-matte",
  "metal-brushed",
  "metal-black",
  "fabric-linen"
]);

const SOLID_BODY_KINDS = new Set([
  "panel",
  "shelf-fixed",
  "box",
  "panel-side",
  "panel-back",
  "panel-bottom",
  "panel-top"
]);

export function normalizeModel(input) {
  const model = Object.assign({
    title: "Interior Design",
    subtitle: "Generated by Interior Design Engine",
    units: "cm",
    width: 300,
    height: 260,
    depth: 60,
    modules: [],
    details: [],
    materials: {}
  }, input || {});

  model.modules = normalizeItems(model.modules, model, "module");
  model.details = normalizeItems(model.details, model, "detail");
  model._validationWarnings = validateMaterialSemantics(model);
  return model;
}

export function normalizeItems(items, model, group) {
  return (items || []).map((item, index) => {
    const normalized = Object.assign({
      id: `${group}-${index + 1}`,
      group,
      kind: "box",
      label: item.type || `${group} ${index + 1}`,
      x: 0,
      y: 0,
      z: 0,
      width: group === "module" ? model.width : 1,
      height: group === "module" ? model.height : 1,
      depth: group === "module" ? model.depth : 1,
      color: item.kind === "void" ? "#ebe4d9" : "#c89a62",
      layer: group === "module" ? 0 : 10,
      csgHints: []
    }, item);
    normalized.csgHints = Array.isArray(normalized.csgHints) ? normalized.csgHints : [];
    return normalized;
  });
}

export function allItems(model) {
  return model.modules.concat(model.details || []);
}

function validateMaterialSemantics(model) {
  const warnings = [];
  allItems(model).forEach((item) => {
    if (item.kind === "void" && SOLID_MATERIAL_REFS.has(item.materialRef)) {
      warnings.push(`${item.id || item.label || "item"}: kind "void" with solid materialRef "${item.materialRef}".`);
    }
    if (item.materialRef === "glass-smoked" && SOLID_BODY_KINDS.has(item.kind)) {
      warnings.push(`${item.id || item.label || "item"}: glass-smoked used on solid body kind "${item.kind}".`);
    }
  });
  return warnings;
}

export function modelBounds(model) {
  const bounds = {
    minX: 0,
    minY: 0,
    minZ: 0,
    maxX: model.width,
    maxY: model.height,
    maxZ: model.depth
  };

  allItems(model).forEach((item) => {
    bounds.minX = Math.min(bounds.minX, item.x);
    bounds.minY = Math.min(bounds.minY, item.y);
    bounds.minZ = Math.min(bounds.minZ, item.z);
    bounds.maxX = Math.max(bounds.maxX, item.x + item.width);
    bounds.maxY = Math.max(bounds.maxY, item.y + item.height);
    bounds.maxZ = Math.max(bounds.maxZ, item.z + item.depth);
  });

  bounds.width = bounds.maxX - bounds.minX;
  bounds.height = bounds.maxY - bounds.minY;
  bounds.depth = bounds.maxZ - bounds.minZ;
  return bounds;
}

export function measureBox(model, mode) {
  const bounds = modelBounds(model);
  if (mode === "front") return { w: bounds.width, h: bounds.height, minA: bounds.minX, minB: bounds.minY };
  if (mode === "side") return { w: bounds.depth, h: bounds.height, minA: bounds.minZ, minB: bounds.minY };
  return { w: bounds.width, h: bounds.depth, minA: bounds.minX, minB: bounds.minZ };
}

export function itemProjection(item, mode, scale, pad, model) {
  const box = measureBox(model, mode);
  const xValue = (mode === "side" ? item.z : item.x) - box.minA;
  const yValue = (mode === "plan" ? item.z : item.y) - box.minB;
  const wValue = mode === "side" ? item.depth : item.width;
  const hValue = mode === "plan" ? item.depth : item.height;
  const yOrigin = mode === "plan" ? yValue : box.h - yValue - hValue;

  return {
    x: pad + xValue * scale,
    y: pad + yOrigin * scale,
    w: Math.max(1, wValue * scale),
    h: Math.max(1, hValue * scale)
  };
}

export function isVisible(item, mode) {
  if (item.onlyIn && !item.onlyIn.includes(mode)) return false;
  if (mode === "front" && item.hiddenInFront) return false;
  if (mode === "side" && item.hiddenInSide) return false;
  if (mode === "plan" && item.hiddenInPlan) return false;
  if (mode === "3d" && item.hiddenIn3d) return false;
  return true;
}
