const SOLID_MATERIAL_REFS = new Set([
  "wood-oak",
  "wood-walnut",
  "laminate-white",
  "laminate-black-matte",
  "metal-brushed",
  "metal-black",
  "fabric-linen"
]);

const SOLID_BODY_KINDS = new Set([
  "panel",
  "shelf-fixed",
  "box",
  "panel-side",
  "panel-back",
  "panel-bottom",
  "panel-top"
]);

const RUN_DIRECTIONS = new Set(["east", "north", "west", "south"]);
const VALID_PALETTES = new Set(["wood-oak", "wood-walnut", "laminate-white", "dark-modern"]);

export function normalizeModel(input) {
  const source = input || {};
  const model = Object.assign({
    title: "Interior Design",
    subtitle: "Generated by Interior Design Engine",
    units: "cm",
    width: 300,
    height: 260,
    depth: 60,
    modules: [],
    runs: [],
    details: [],
    materials: {},
    palette: "wood-oak",
    inlineTemplates: {}
  }, source);

  model.palette = VALID_PALETTES.has(source.palette) ? source.palette : "wood-oak";
  model.inlineTemplates = source.inlineTemplates && typeof source.inlineTemplates === "object" && !Array.isArray(source.inlineTemplates)
    ? source.inlineTemplates
    : {};
  model.runs = normalizeRuns(source, model);
  model.modules = model.runs.flatMap((run) => run.modules);
  model.details = normalizeItems(model.details, model, "detail");
  model._validationWarnings = validateMaterialSemantics(model);
  if (source.palette && source.palette !== model.palette) model._validationWarnings.push(`Unknown palette "${source.palette}", using wood-oak.`);
  return model;
}

function normalizeRuns(source, model) {
  const hasRuns = Array.isArray(source.runs) && source.runs.length > 0;
  const rawRuns = hasRuns
    ? source.runs
    : [{ id: "default", origin: { x: 0, z: 0 }, direction: "east", modules: source.modules || [] }];

  return rawRuns.map((run, runIndex) => {
    const direction = RUN_DIRECTIONS.has(run.direction) ? run.direction : "east";
    const normalizedRun = {
      id: run.id || `run-${runIndex + 1}`,
      origin: {
        x: Number.isFinite(run.origin && run.origin.x) ? run.origin.x : 0,
        z: Number.isFinite(run.origin && run.origin.z) ? run.origin.z : 0
      },
      direction,
      modules: []
    };
    const modules = normalizeItems(run.modules || [], model, "module");
    normalizedRun.modules = modules
      .map((item, moduleIndex) => {
        const coord = resolveRunCoord(Object.assign({}, normalizedRun, { modules }), moduleIndex, item);
        return Object.assign({}, item, coord, {
          _runId: normalizedRun.id,
          _runIndex: runIndex,
          _runModuleIndex: moduleIndex,
          _runDirection: direction
        });
      });
    return normalizedRun;
  });
}

export function normalizeItems(items, model, group) {
  return (items || []).map((item, index) => {
    const normalized = Object.assign({
      id: `${group}-${index + 1}`,
      group,
      kind: "box",
      label: item.type || `${group} ${index + 1}`,
      x: 0,
      y: 0,
      z: 0,
      width: group === "module" ? model.width : 1,
      height: group === "module" ? model.height : 1,
      depth: group === "module" ? model.depth : 1,
      color: item.kind === "void" ? "#ebe4d9" : "#c89a62",
      layer: group === "module" ? 0 : 10
    }, item);
    normalized.style = normalized.style && typeof normalized.style === "object" && !Array.isArray(normalized.style) ? normalized.style : {};
    if (typeof normalized.tpl === "string" && normalized.tpl.trim()) {
      normalized.tpl = normalized.tpl.trim();
      normalized._isTemplate = true;
    }
    return normalized;
  });
}

export function allItems(model) {
  // Multi-run models must surface every module in every view. Earlier code
  // returned only runs[0] for front/side which silently dropped perpendicular
  // runs (L-shape kitchen return-run, etc) from those projections. The 2D
  // projection logic in itemProjection/itemFootprint already handles direction,
  // so passing all modules is safe.
  return (model.modules || []).concat(model.details || []);
}

export function resolveRunCoord(run, moduleIndex, item) {
  const modules = Array.isArray(run.modules) ? run.modules : [];
  const current = item || modules[moduleIndex] || {};
  const origin = run.origin || {};
  const isResolved = !!current._runDirection;
  const localX = !isResolved && Number.isFinite(current.x) ? current.x : 0;
  const localY = Number.isFinite(current.y) ? current.y : 0;
  const localZ = !isResolved && Number.isFinite(current.z) ? current.z : 0;
  const originX = Number.isFinite(origin.x) ? origin.x : 0;
  const originZ = Number.isFinite(origin.z) ? origin.z : 0;
  // Heuristic: if any module in run already carries explicit along-axis position,
  // treat local x/z as ABSOLUTE within run frame. Otherwise fall back to
  // index-based auto-offset (legacy convention from Phase 8 single-module runs).
  const alongAxisKey = run.direction === "north" || run.direction === "south" ? "z" : "x";
  const hasExplicitAlong = modules.some((m) => Number.isFinite(m[alongAxisKey]) && m[alongAxisKey] > 0);
  const offset = hasExplicitAlong
    ? 0
    : modules.slice(0, moduleIndex).reduce((sum, module) => sum + (module.width || 0), 0);
  if (run.direction === "north") return { x: originX + localX, y: localY, z: originZ - offset + localZ };
  if (run.direction === "west") return { x: originX - offset + localX, y: localY, z: originZ + localZ };
  if (run.direction === "south") return { x: originX + localX, y: localY, z: originZ + offset + localZ };
  return { x: originX + offset + localX, y: localY, z: originZ + localZ };
}

export function itemFootprint(item) {
  const direction = item._runDirection || "east";
  if (direction === "north") {
    return { minX: item.x, maxX: item.x + item.depth, minZ: item.z - item.width, maxZ: item.z };
  }
  if (direction === "west") {
    return { minX: item.x - item.width, maxX: item.x, minZ: item.z, maxZ: item.z + item.depth };
  }
  if (direction === "south") {
    return { minX: item.x, maxX: item.x + item.depth, minZ: item.z, maxZ: item.z + item.width };
  }
  return { minX: item.x, maxX: item.x + item.width, minZ: item.z, maxZ: item.z + item.depth };
}

function validateMaterialSemantics(model) {
  const warnings = [];
  allItems(model).forEach((item) => {
    if (item._isTemplate) return;
    if (item.kind === "void" && SOLID_MATERIAL_REFS.has(item.materialRef)) {
      warnings.push(`${item.id || item.label || "item"}: kind "void" with solid materialRef "${item.materialRef}".`);
    }
    if (item.materialRef === "glass-smoked" && SOLID_BODY_KINDS.has(item.kind)) {
      warnings.push(`${item.id || item.label || "item"}: glass-smoked used on solid body kind "${item.kind}".`);
    }
  });
  return warnings;
}

export function modelBounds(model, mode) {
  const bounds = {
    minX: 0,
    minY: 0,
    minZ: 0,
    maxX: model.width,
    maxY: model.height,
    maxZ: model.depth
  };

  allItems(model, mode).forEach((item) => {
    const footprint = itemFootprint(item);
    bounds.minX = Math.min(bounds.minX, footprint.minX);
    bounds.minY = Math.min(bounds.minY, item.y);
    bounds.minZ = Math.min(bounds.minZ, footprint.minZ);
    bounds.maxX = Math.max(bounds.maxX, footprint.maxX);
    bounds.maxY = Math.max(bounds.maxY, item.y + item.height);
    bounds.maxZ = Math.max(bounds.maxZ, footprint.maxZ);
  });

  bounds.width = bounds.maxX - bounds.minX;
  bounds.height = bounds.maxY - bounds.minY;
  bounds.depth = bounds.maxZ - bounds.minZ;
  return bounds;
}

export function measureBox(model, mode) {
  const bounds = modelBounds(model, mode);
  if (mode === "front") return { w: bounds.width, h: bounds.height, minA: bounds.minX, minB: bounds.minY };
  if (mode === "side") return { w: bounds.depth, h: bounds.height, minA: bounds.minZ, minB: bounds.minY };
  return { w: bounds.width, h: bounds.depth, minA: bounds.minX, minB: bounds.minZ };
}

export function itemProjection(item, mode, scale, pad, model) {
  const box = measureBox(model, mode);
  const footprint = itemFootprint(item);
  const xValue = (mode === "side" ? footprint.minZ : footprint.minX) - box.minA;
  const yValue = (mode === "plan" ? footprint.minZ : item.y) - box.minB;
  const wValue = mode === "side" ? footprint.maxZ - footprint.minZ : footprint.maxX - footprint.minX;
  const hValue = mode === "plan" ? footprint.maxZ - footprint.minZ : item.height;
  const yOrigin = mode === "plan" ? yValue : box.h - yValue - hValue;

  return {
    x: pad + xValue * scale,
    y: pad + yOrigin * scale,
    w: Math.max(1, wValue * scale),
    h: Math.max(1, hValue * scale)
  };
}

export function isVisible(item, mode) {
  if (item.onlyIn && !item.onlyIn.includes(mode)) return false;
  if (mode === "front" && item.hiddenInFront) return false;
  if (mode === "side" && item.hiddenInSide) return false;
  if (mode === "plan" && item.hiddenInPlan) return false;
  if (mode === "3d" && item.hiddenIn3d) return false;
  return true;
}
